/**
 * build-css.mjs — Concatenate and minify CSS modules.
 *
 * Reads src/styles/index.css, resolves @import statements,
 * concatenates all modules in order, and writes:
 *   dist/md-render.css       (unminified, with banner)
 *   dist/md-render.min.css   (csso-minified)
 *   src/styles/inline.generated.js    (baked CSS string for JS bundle)
 *
 * Run: node scripts/build-css.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { minify } from "csso";

const SRC_DIR = resolve("src/styles");
const DIST_DIR = resolve("dist");
const INDEX_CSS = resolve(SRC_DIR, "index.css");

/** License banner prepended to the unminified CSS bundle. */
const BANNER = `/**
 * md-render v${readFileSync(resolve("package.json"), "utf8").match(/"version":\s*"([^"]+)"/)[1]}
 * CSS bundle — concatenated from src/styles/
 * License: MIT
 */
`;

/**
 * Resolve @import statements in a CSS file and return the full concatenated text.
 * Imports are resolved relative to the source file's directory.
 *
 * @param {string} filePath - Absolute path to a CSS file
 * @param {Map<string, string>} [cache] - Deduplication cache
 * @returns {string} Concatenated CSS text
 */
function resolveImports(filePath, cache = new Map()) {
  if (cache.has(filePath)) return cache.get(filePath);

  const raw = readFileSync(filePath, "utf8");
  const dir = dirname(filePath);
  const importRe = /@import\s+"([^"]+)";?\s*/g;

  let result = "";
  let match;
  let lastIdx = 0;

  while ((match = importRe.exec(raw)) !== null) {
    // Include any text before this import
    result += raw.slice(lastIdx, match.index);
    // Recursively resolve the imported file
    const importedPath = resolve(dir, match[1]);
    result += resolveImports(importedPath, cache);
    lastIdx = importRe.lastIndex;
  }

  // Include remaining text after the last import
  result += raw.slice(lastIdx);
  cache.set(filePath, result);
  return result;
}

/* ── Main ── */

console.log("build-css: reading", INDEX_CSS);

const cssText = resolveImports(INDEX_CSS);
const unminified = BANNER + cssText;

// Ensure dist/ exists
mkdirSync(DIST_DIR, { recursive: true });

// Write unminified
writeFileSync(resolve(DIST_DIR, "md-render.css"), unminified, "utf8");
console.log("build-css: wrote dist/md-render.css");

// Write minified
try {
  const result = minify(cssText);
  writeFileSync(
    resolve(DIST_DIR, "md-render.min.css"),
    result.css,
    "utf8"
  );
  console.log("build-css: wrote dist/md-render.min.css");
} catch (err) {
  console.error("build-css: csso minification failed:", err.message);
  process.exit(1);
}

// Write inline.generated.js (baked CSS string for JS bundle)
const inlineJs = `/**
 * inline.generated.js — AUTO-GENERATED by scripts/build-css.mjs
 * Do NOT edit or commit. Added to .gitignore.
 */
export default ${JSON.stringify(cssText)};
`;
writeFileSync(resolve(SRC_DIR, "inline.generated.js"), inlineJs, "utf8");
console.log("build-css: wrote src/styles/inline.generated.js");

// Print sizes
const { statSync } = await import("node:fs");
const cssSize = statSync(resolve(DIST_DIR, "md-render.css")).size;
const minSize = statSync(resolve(DIST_DIR, "md-render.min.css")).size;
console.log(`build-css: ${cssSize.toLocaleString()} B unminified, ${minSize.toLocaleString()} B minified`);
